### ISSUE TITLE
models/Folder.php uses non-existent humhub\modules\file\libs\ImageConverter class

### ISSUE THREAD

**Issue by globalcow** [humhub/humhub-modules-cfiles#87]
The class humhub\modules\file\libs\ImageConverter is not available anymore since Humhub 1.5
The class is still used in https://github.com/humhub/humhub-modules-cfiles/blob/980240dd8c8b5560625becf057f2ef65902e54f0/models/Folder.php#L5

It is not possible to import ZIP-Files containing JPG files.

**Comment by MasterMindNET** [comment]
Which class or module we should use instead of this?
Any advice?

Thank you!

**Comment by luke-** [comment]
The ImageConverter class was replaced with https://github.com/yiisoft/yii2-imagine

Here some example code how to use:
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/file/converter/PreviewImage.php#L83

Make sure to increase the `min HumHub Version` to `1.6` with this PR. Since the Imagine was not available in earlier versions.
